const { cmd, commands } = require("../command");
const config = require("../config");

cmd(
  {
    pattern: "menu",
    alias: ["getmenu"],
    react: "📔",
    desc: "Get simple welcome menu",
    category: "main",
    filename: __filename,
  },

  async (
    robin,
    mek,
    m,
    {
      from,
      sender,
      reply,
    }
  ) => {
    try {
      // ==========================================
      // NATIVE FLOW INTERACTIVE 4 BUTTONS WITH IMAGE
      // ==========================================
      const { generateWAMessageFromContent, proto, prepareWAMessageMedia } = require("@whiskeysockets/baileys");

      // 🔘 ඔයාගේ පැරණි බ්ටන් දෙක සමඟ අලුත් බ්ටන් දෙකම මෙතැනට ඇතුළත් කර ඇත (බ්ටන් 4ම ඇත)
      const buttons = [
        {
          "name": "quick_reply",
          "buttonParamsJson": JSON.stringify({
            "display_text": "MAIN MENU 📜",
            "id": ".menu"
          })
        },
        {
          "name": "quick_reply",
          "buttonParamsJson": JSON.stringify({
            "display_text": "PING ⚡",
            "id": ".ping"
          })
        },
        {
          "name": "quick_reply",
          "buttonParamsJson": JSON.stringify({
            "display_text": "ALIVE 🧚‍♂️",
            "id": ".alive"
          })
        },
        {
          "name": "quick_reply",
          "buttonParamsJson": JSON.stringify({
            "display_text": "BOT OWNER 👑",
            "id": ".owner"
          })
        }
      ];

      // ඔයාගේ මුල් ලින්ක් එකෙන්ම ඉමේජ් එක සකස් කිරීම
      const mediaMessage = await prepareWAMessageMedia(
        { image: { url: "https://i.ibb.co/mVHr7tm2/image.jpg" } }, 
        { upload: robin.waUploadToServer }
      );

      const msg = generateWAMessageFromContent(from, {
        viewOnceMessage: {
          message: {
            messageContextInfo: {
              deviceListMetadata: {},
              deviceListMetadataVersion: 2
            },
            interactiveMessage: proto.Message.InteractiveMessage.fromObject({
              body: proto.Message.InteractiveMessage.Body.fromObject({
                text: "👋 *Hello welcome to DENETH-MD*\n\n> *Generated by DENETH-MD* 💢" // මුල්ම caption එක වෙනස් නොකර තබා ඇත
              }),
              footer: proto.Message.InteractiveMessage.Footer.fromObject({
                text: "© Powered By Deneth MD"
              }),
              header: proto.Message.InteractiveMessage.Header.fromObject({
                hasMediaAttachment: true,
                imageMessage: mediaMessage.imageMessage
              }),
              nativeFlowMessage: proto.Message.InteractiveMessage.NativeFlowMessage.fromObject({
                buttons: buttons
              }),
              contextInfo: {
                mentionedJid: sender ? [sender] : [],
                forwardingScore: 1000,
                isForwarded: true,
                forwardedNewsletterMessageInfo: {
                  newsletterJid: "120363429118791328@newsletter",
                  newsletterName: "DENETH 𝐌𝐃",
                  serverMessageId: 143,
                },
              },
            })
          }
        }
      }, { userJid: robin.user.jid, quoted: mek });

      // මැසේජ් එක වට්ස්ඇප් වෙත යැවීම
      await robin.relayMessage(from, msg.message, { messageId: msg.key.id });

    } catch (e) {
      console.error("MENU ERROR:", e);
      reply(`❌ Menu Error\n\n${e.message || e}`);
    }
  }
);
