const { cmd, commands } = require("../command");
const config = require("../config");

// ==========================================
// ප්‍රධාන MENU විධානය (TEXT & NUMBERS ක්‍රමයට)
// ==========================================
cmd(
  {
    pattern: "menu",
    alias: ["getmenu"],
    react: "📔",
    desc: "Get simple text-based category menu",
    category: "main",
    filename: __filename,
  },

  async (robin, mek, m, { from, reply }) => {
    try {
      // ලස්සන Text Menu එකක් සාදා ගැනීම
      let menuText = `👋 *Hello welcome to DENETH-MD*\n\n` +
                     `> *Generated by DENETH-MD* 💢\n\n` +
                     ` नीचे තියෙන අංක වලින් ඔබට අවශ්‍ය Category එක තෝරා එහි අංකය Reply කරන්න. 👇\n\n` +
                     `[1] 📊 ALL COMMANDS\n` +
                     `[2] ⬇️ DOWNLOAD MENU\n` +
                     `[3] 👥 GROUP MENU\n` +
                     `[4] 👑 OWNER MENU\n` +
                     `[5] 🎨 CONVERT MENU\n\n` +
                     `© Powered By Deneth MD`;

      // ඉමේජ් එකත් සමඟ Text එක යැවීම
      return await robin.sendMessage(from, { 
          image: { url: "https://ibb.co" }, 
          caption: menuText 
      }, { quoted: mek });

    } catch (e) {
      console.error("MENU ERROR:", e);
      reply(`❌ Menu Error\n\n${e.message || e}`);
    }
  }
);

// ==========================================
// යූසර් අංකයක් (1, 2, 3) රිප්ලයි කළ විට ක්‍රියාත්මක වන කොටස
// ==========================================
cmd({
    on: "text",
    dontAddCommandList: true,
    filename: __filename
}, async (robin, mek, m, { from, reply, body }) => {
    try {
        if (!body || m.isBot) return; // බොට් කෙනෙක් රිප්ලයි කළොත් නවත්වන්න

        const input = body.trim();
        let menuMessage = "";

        if (input === "1") {
            menuMessage = `📊 *DENETH-MD ALL COMMANDS LIST* 📊\n\n`;
            commands.map((cmd) => {
                if (!cmd.dontAddCommandList && cmd.pattern) {
                    menuMessage += `▪️ *Command:* .${cmd.pattern}\n▪️ *Desc:* ${cmd.desc || 'No description'}\n\n`;
                }
            });
            return await robin.sendMessage(from, { text: menuMessage }, { quoted: mek });
        } 
        
        else if (input === "2") {
            menuMessage = `✨ *DENETH-MD DOWNLOAD MENU* ✨\n\n`;
            commands.map((cmd) => {
                if (!cmd.dontAddCommandList && cmd.pattern && cmd.category && cmd.category.toLowerCase() === "download") {
                    menuMessage += `▪️ *Command:* .${cmd.pattern}\n▪️ *Desc:* ${cmd.desc || 'No description'}\n\n`;
                }
            });
            return await robin.sendMessage(from, { text: menuMessage }, { quoted: mek });
        }

        else if (input === "3") {
            menuMessage = `✨ *DENETH-MD GROUP MENU* ✨\n\n`;
            commands.map((cmd) => {
                if (!cmd.dontAddCommandList && cmd.pattern && cmd.category && cmd.category.toLowerCase() === "group") {
                    menuMessage += `▪️ *Command:* .${cmd.pattern}\n▪️ *Desc:* ${cmd.desc || 'No description'}\n\n`;
                }
            });
            return await robin.sendMessage(from, { text: menuMessage }, { quoted: mek });
        }

        else if (input === "4") {
            menuMessage = `✨ *DENETH-MD OWNER MENU* ✨\n\n`;
            commands.map((cmd) => {
                if (!cmd.dontAddCommandList && cmd.pattern && cmd.category && cmd.category.toLowerCase() === "owner") {
                    menuMessage += `▪️ *Command:* .${cmd.pattern}\n▪️ *Desc:* ${cmd.desc || 'No description'}\n\n`;
                }
            });
            return await robin.sendMessage(from, { text: menuMessage }, { quoted: mek });
        }

        else if (input === "5") {
            menuMessage = `✨ *DENETH-MD CONVERT MENU* ✨\n\n`;
            commands.map((cmd) => {
                if (!cmd.dontAddCommandList && cmd.pattern && cmd.category && cmd.category.toLowerCase() === "convert") {
                    menuMessage += `▪️ *Command:* .${cmd.pattern}\n▪️ *Desc:* ${cmd.desc || 'No description'}\n\n`;
                }
            });
            return await robin.sendMessage(from, { text: menuMessage }, { quoted: mek });
        }

    } catch (e) {
        console.error("TEXT MENU ERROR:", e);
    }
});
