const { cmd, commands } = require("../command");
const config = require("../config");

cmd(
  {
    pattern: "menu",
    alias: ["getmenu"],
    react: "📔",
    desc: "Get categories list menu",
    category: "main",
    filename: __filename,
  },

  async (
    robin,
    mek,
    m,
    {
      from,
      sender,
      reply,
    }
  ) => {
    try {
      // ==========================================
      // NATIVE FLOW INTERACTIVE SELECT MENU
      // ==========================================
      const { generateWAMessageFromContent, proto, prepareWAMessageMedia } = require("@whiskeysockets/baileys");

      // 🔘 මෙන්න ඔයා ඉල්ලපු විදියට OPEN MENU බටන් එක සහ Categories ටික
      const buttons = [
        {
          "name": "single_select_reply",
          "buttonParamsJson": JSON.stringify({
            "title": "OPEN MENU 📜", // යටින් පෙනෙන ප්‍රධාන බටන් එක
            "sections": [
              {
                "title": "🤖 BOT MAIN CATEGORIES", // ලිස්ට් එකේ උඩින්ම වැටෙන මාතෘකාව
                "rows": [
                  {
                    "title": "ALL COMMANDS 📊",
                    "description": "බොට්ගේ සියලුම විධාන ලබා ගැනීමට",
                    "id": ".allmenu"
                  },
                  {
                    "title": "DOWNLOAD MENU ⬇️",
                    "description": "Video, Audio download විධාන ලබා ගැනීමට",
                    "id": ".downmenu"
                  },
                  {
                    "title": "GROUP MENU 👥",
                    "description": "Group කළමනාකරණය කරන විධාන ලබා ගැනීමට",
                    "id": ".groupmenu"
                  },
                  {
                    "title": "OWNER MENU 👑",
                    "description": "බොට් අයිතිකරුට පමණක් අදාළ විධාන",
                    "id": ".ownermenu"
                  },
                  {
                    "title": "CONVERT MENU 🎨",
                    "description": "Stickers, Logo සාදන විධාන ලබා ගැනීමට",
                    "id": ".convertmenu"
                  }
                ]
              }
            ]
          })
        }
      ];

      // ඔයාගේ මුල් ලින්ක් එකෙන්ම ඉමේජ් එක සකස් කිරීම
      const mediaMessage = await prepareWAMessageMedia(
        { image: { url: "https://ibb.co" } }, 
        { upload: robin.waUploadToServer }
      );

      const msg = generateWAMessageFromContent(from, {
        viewOnceMessage: {
          message: {
            messageContextInfo: {
              deviceListMetadata: {},
              deviceListMetadataVersion: 2
            },
            interactiveMessage: proto.Message.InteractiveMessage.fromObject({
              body: proto.Message.InteractiveMessage.Body.fromObject({
                text: "👋 *Hello welcome to DENETH-MD*\n\n> *Generated by DENETH-MD* 💢"
              }),
              footer: proto.Message.InteractiveMessage.Footer.fromObject({
                text: "© Powered By Deneth MD"
              }),
              header: proto.Message.InteractiveMessage.Header.fromObject({
                hasMediaAttachment: true,
                imageMessage: mediaMessage.imageMessage
              }),
              nativeFlowMessage: proto.Message.InteractiveMessage.NativeFlowMessage.fromObject({
                buttons: buttons
              }),
              contextInfo: {
                mentionedJid: sender ? [sender] : [],
                forwardingScore: 1000,
                isForwarded: true,
                forwardedNewsletterMessageInfo: {
                  newsletterJid: "120363429118791328@newsletter",
                  newsletterName: "DENETH 𝐌𝐃",
                  serverMessageId: 143,
                },
              },
            })
          }
        }
      }, { userJid: robin.user.jid, quoted: mek });

      // මැසේජ් එක වට්ස්ඇප් වෙත යැවීම
      await robin.relayMessage(from, msg.message, { messageId: msg.key.id });

    } catch (e) {
      console.error("MENU ERROR:", e);
      reply(`❌ Menu Error\n\n${e.message || e}`);
    }
  }
);
